<?php

namespace Database\Seeders;

use App\Models\LandingFaq;
use Illuminate\Database\Seeder;

class LandingFaqSeeder extends Seeder
{
    public function run(): void
    {
        // Utiliser updateOrCreate pour ne pas dupliquer en cas de re-seed
        $faqs = [
            // ── Général ──────────────────────────────────────────────────────
            ['category' => 'general', 'sort_order' => 1,
                'question_fr' => "Qu'est-ce que CONSTRUIRO ?",
                'answer_fr'   => "CONSTRUIRO est un ERP (Enterprise Resource Planning) 100 % en ligne dédié aux entreprises du BTP et de la construction. Il regroupe en une seule plateforme la gestion de projets, la facturation, les RH, la trésorerie, les stocks, le QHSE, la BI et bien plus encore.",
                'question_en' => "What is CONSTRUIRO?",
                'answer_en'   => "CONSTRUIRO is a 100% online ERP dedicated to construction companies. It brings together project management, invoicing, HR, treasury, stock, QHSE, BI and more in a single platform.",
            ],
            ['category' => 'general', 'sort_order' => 2,
                'question_fr' => "CONSTRUIRO est-il adapté aux PME ?",
                'answer_fr'   => "Oui. CONSTRUIRO a été conçu spécifiquement pour les PME et ETI du secteur BTP en Afrique et ailleurs. Les plans Solo et Starter sont idéaux pour les petites structures, tandis que les plans Pro et Entreprise s'adressent aux sociétés avec plusieurs agences.",
                'question_en' => "Is CONSTRUIRO suitable for SMEs?",
                'answer_en'   => "Yes. CONSTRUIRO was specifically designed for SMEs in the construction sector in Africa and beyond. The Solo and Starter plans are ideal for small firms, while Pro and Enterprise plans target companies with multiple branches.",
            ],
            ['category' => 'general', 'sort_order' => 3,
                'question_fr' => "Puis-je utiliser CONSTRUIRO depuis mon smartphone ?",
                'answer_fr'   => "Oui. CONSTRUIRO est une Progressive Web App (PWA). Vous pouvez l'installer sur votre téléphone Android ou iPhone depuis votre navigateur et l'utiliser même avec une connexion lente.",
                'question_en' => "Can I use CONSTRUIRO from my smartphone?",
                'answer_en'   => "Yes. CONSTRUIRO is a Progressive Web App (PWA). You can install it on your Android or iPhone from your browser and use it even with a slow connection.",
            ],
            ['category' => 'general', 'sort_order' => 4,
                'question_fr' => "CONSTRUIRO fonctionne-t-il hors ligne ?",
                'answer_fr'   => "Les pages déjà consultées sont mises en cache et restent accessibles hors ligne. La création et la synchronisation de données nécessitent cependant une connexion Internet.",
                'question_en' => "Does CONSTRUIRO work offline?",
                'answer_en'   => "Pages already visited are cached and remain accessible offline. However, creating and syncing data requires an internet connection.",
            ],
            ['category' => 'general', 'sort_order' => 5,
                'question_fr' => "Dans quels pays CONSTRUIRO est-il disponible ?",
                'answer_fr'   => "CONSTRUIRO est disponible partout dans le monde. Il est particulièrement optimisé pour les marchés d'Afrique subsaharienne, du Maghreb et des pays francophones.",
                'question_en' => "In which countries is CONSTRUIRO available?",
                'answer_en'   => "CONSTRUIRO is available worldwide. It is particularly optimised for sub-Saharan Africa, the Maghreb and French-speaking countries.",
            ],

            // ── Tarifs & Plans ────────────────────────────────────────────────
            ['category' => 'tarifs', 'sort_order' => 10,
                'question_fr' => "Quels sont les plans disponibles ?",
                'answer_fr'   => "CONSTRUIRO propose 4 plans : Solo (1 utilisateur), Starter (jusqu'à 5), Pro (jusqu'à 20) et Entreprise (utilisateurs illimités). Chaque plan est disponible en facturation mensuelle ou annuelle (2 mois offerts).",
                'question_en' => "What plans are available?",
                'answer_en'   => "CONSTRUIRO offers 4 plans: Solo (1 user), Starter (up to 5), Pro (up to 20) and Enterprise (unlimited users). Each plan is available with monthly or annual billing (2 months free).",
            ],
            ['category' => 'tarifs', 'sort_order' => 11,
                'question_fr' => "Y a-t-il un essai gratuit ?",
                'answer_fr'   => "Oui. Tous les plans bénéficient d'un essai gratuit de 14 jours sans carte bancaire requise.",
                'question_en' => "Is there a free trial?",
                'answer_en'   => "Yes. All plans include a 14-day free trial with no credit card required.",
            ],
            ['category' => 'tarifs', 'sort_order' => 12,
                'question_fr' => "Puis-je changer de plan en cours d'abonnement ?",
                'answer_fr'   => "Oui, vous pouvez monter en plan (upgrade) à tout moment depuis la page Abonnement. Le changement prend effet immédiatement et la différence est calculée au prorata.",
                'question_en' => "Can I change my plan during my subscription?",
                'answer_en'   => "Yes, you can upgrade at any time from the Subscription page. The change takes effect immediately and the difference is calculated pro-rata.",
            ],
            ['category' => 'tarifs', 'sort_order' => 13,
                'question_fr' => "Quels modes de paiement sont acceptés ?",
                'answer_fr'   => "Nous acceptons Orange Money, MTN MoMo, Wave et les virements bancaires. Les paiements par carte bancaire internationale seront disponibles prochainement.",
                'question_en' => "What payment methods are accepted?",
                'answer_en'   => "We accept Orange Money, MTN MoMo, Wave and bank transfers. International card payments will be available soon.",
            ],
            ['category' => 'tarifs', 'sort_order' => 14,
                'question_fr' => "Que se passe-t-il à l'expiration de l'abonnement ?",
                'answer_fr'   => "À l'expiration, vous entrez dans une période de grâce de 7 jours pendant laquelle vos données restent accessibles. Passé ce délai, l'accès est suspendu mais vos données sont conservées pendant 90 jours.",
                'question_en' => "What happens when my subscription expires?",
                'answer_en'   => "On expiry, you enter a 7-day grace period during which your data remains accessible. After that, access is suspended but your data is kept for 90 days.",
            ],

            // ── Projets ────────────────────────────────────────────────────────
            ['category' => 'projets', 'sort_order' => 20,
                'question_fr' => "Comment créer un nouveau projet ?",
                'answer_fr'   => "Rendez-vous dans le menu Projets, cliquez sur « Nouveau projet » et renseignez le nom, le code projet, le chef de projet et les dates prévisionnelles. Vous pouvez ensuite ajouter des sites, des tâches et des ressources.",
                'question_en' => "How do I create a new project?",
                'answer_en'   => "Go to the Projects menu, click 'New Project' and fill in the name, project code, project manager and estimated dates. You can then add sites, tasks and resources.",
            ],
            ['category' => 'projets', 'sort_order' => 21,
                'question_fr' => "Puis-je gérer plusieurs chantiers (sites) par projet ?",
                'answer_fr'   => "Oui. Chaque projet peut contenir plusieurs sites géographiques avec leurs propres équipes, avancement et documents.",
                'question_en' => "Can I manage multiple sites per project?",
                'answer_en'   => "Yes. Each project can contain multiple geographical sites with their own teams, progress and documents.",
            ],
            ['category' => 'projets', 'sort_order' => 22,
                'question_fr' => "Comment suivre l'avancement d'un projet ?",
                'answer_fr'   => "Le tableau de bord de chaque projet affiche le pourcentage d'avancement global, les jalons, les tâches en retard et les indicateurs clés (budget, dépenses, équipe).",
                'question_en' => "How do I track project progress?",
                'answer_en'   => "Each project dashboard shows overall completion percentage, milestones, overdue tasks and key indicators (budget, expenses, team).",
            ],
            ['category' => 'projets', 'sort_order' => 23,
                'question_fr' => "Peut-on attacher des documents à un projet ?",
                'answer_fr'   => "Oui. Le module GED intégré permet d'attacher des plans, des contrats, des photos de chantier et tout autre document à un projet ou à un site.",
                'question_en' => "Can I attach documents to a project?",
                'answer_en'   => "Yes. The integrated DMS allows you to attach plans, contracts, site photos and any other documents to a project or site.",
            ],
            ['category' => 'projets', 'sort_order' => 24,
                'question_fr' => "Comment gérer les budgets de projet ?",
                'answer_fr'   => "Depuis la fiche projet, vous pouvez saisir le budget prévisionnel, puis suivre les engagements (commandes, sous-traitance) et les dépenses réelles en temps réel.",
                'question_en' => "How do I manage project budgets?",
                'answer_en'   => "From the project sheet, you can enter the forecast budget, then track commitments (orders, subcontracting) and actual expenses in real time.",
            ],

            // ── Facturation ────────────────────────────────────────────────────
            ['category' => 'facturation', 'sort_order' => 30,
                'question_fr' => "Comment créer une facture ?",
                'answer_fr'   => "Dans le menu Facturation, cliquez sur « Nouvelle facture ». Sélectionnez le client, ajoutez les lignes de prestation, appliquez la TVA et validez. La facture est générée en PDF et peut être envoyée directement par email.",
                'question_en' => "How do I create an invoice?",
                'answer_en'   => "In the Invoicing menu, click 'New Invoice'. Select the client, add service lines, apply VAT and validate. The invoice is generated as a PDF and can be sent directly by email.",
            ],
            ['category' => 'facturation', 'sort_order' => 31,
                'question_fr' => "CONSTRUIRO gère-t-il les devis ?",
                'answer_fr'   => "Oui. Vous pouvez créer des devis, les envoyer aux clients, et les convertir en factures en un clic lorsqu'ils sont acceptés.",
                'question_en' => "Does CONSTRUIRO handle quotes?",
                'answer_en'   => "Yes. You can create quotes, send them to clients, and convert them to invoices with one click when accepted.",
            ],
            ['category' => 'facturation', 'sort_order' => 32,
                'question_fr' => "Peut-on gérer les acomptes et les situations de travaux ?",
                'answer_fr'   => "Oui. CONSTRUIRO prend en charge les factures d'acompte, les situations de travaux (avancement partiel) et les factures de solde.",
                'question_en' => "Can I manage advance payments and progress billing?",
                'answer_en'   => "Yes. CONSTRUIRO supports advance invoices, progress billing (partial completion) and final invoices.",
            ],
            ['category' => 'facturation', 'sort_order' => 33,
                'question_fr' => "Les factures sont-elles conformes aux normes fiscales ?",
                'answer_fr'   => "Les factures incluent tous les champs requis (numéro séquentiel, TVA, mentions légales). Elles peuvent être adaptées aux exigences fiscales locales de chaque pays.",
                'question_en' => "Are invoices compliant with tax standards?",
                'answer_en'   => "Invoices include all required fields (sequential number, VAT, legal notices). They can be adapted to the local tax requirements of each country.",
            ],
            ['category' => 'facturation', 'sort_order' => 34,
                'question_fr' => "Comment enregistrer un paiement reçu ?",
                'answer_fr'   => "Depuis la liste des factures ou la fiche client, cliquez sur « Encaisser » pour enregistrer un paiement partiel ou total. Le statut de la facture se met à jour automatiquement.",
                'question_en' => "How do I record a received payment?",
                'answer_en'   => "From the invoice list or client file, click 'Record payment' to register a partial or full payment. The invoice status updates automatically.",
            ],

            // ── RH ────────────────────────────────────────────────────────────
            ['category' => 'rh', 'sort_order' => 40,
                'question_fr' => "Quelles fonctionnalités RH sont disponibles ?",
                'answer_fr'   => "CONSTRUIRO couvre la gestion des employés, les contrats, les fiches de paie, les pointages, la planification des équipes, les congés et absences.",
                'question_en' => "What HR features are available?",
                'answer_en'   => "CONSTRUIRO covers employee management, contracts, payslips, timesheets, team planning, leave and absences.",
            ],
            ['category' => 'rh', 'sort_order' => 41,
                'question_fr' => "Comment générer une fiche de paie ?",
                'answer_fr'   => "Dans le module RH → Fiches de paie, sélectionnez l'employé et le mois, vérifiez les heures et les primes, puis cliquez sur « Générer ». La fiche est disponible en PDF et peut être envoyée par email.",
                'question_en' => "How do I generate a payslip?",
                'answer_en'   => "In HR → Payslips, select the employee and month, check hours and bonuses, then click 'Generate'. The payslip is available as PDF and can be emailed.",
            ],
            ['category' => 'rh', 'sort_order' => 42,
                'question_fr' => "Peut-on gérer les pointages depuis le chantier ?",
                'answer_fr'   => "Oui. Le module Pointage permet aux chefs de chantier de saisir les présences directement depuis leur smartphone, même avec une connexion limitée.",
                'question_en' => "Can timesheets be managed from the site?",
                'answer_en'   => "Yes. The Timesheet module allows site managers to enter attendance directly from their smartphone, even with a limited connection.",
            ],
            ['category' => 'rh', 'sort_order' => 43,
                'question_fr' => "Comment affecter un employé à un projet ?",
                'answer_fr'   => "Dans le module Planning, vous pouvez affecter des employés à des projets et des sites avec des dates de début et de fin. Le tableau de planning visualise les affectations de toute l'équipe.",
                'question_en' => "How do I assign an employee to a project?",
                'answer_en'   => "In the Planning module, you can assign employees to projects and sites with start and end dates. The planning board visualises the whole team's assignments.",
            ],

            // ── Stocks ────────────────────────────────────────────────────────
            ['category' => 'stocks', 'sort_order' => 50,
                'question_fr' => "Comment gérer les stocks de matériaux ?",
                'answer_fr'   => "Le module Stocks permet de gérer les entrepôts, les articles, les mouvements d'entrée/sortie et les transferts inter-dépôts. Des alertes de stock minimum sont configurables.",
                'question_en' => "How do I manage material stock?",
                'answer_en'   => "The Stock module lets you manage warehouses, items, in/out movements and inter-warehouse transfers. Minimum stock alerts are configurable.",
            ],
            ['category' => 'stocks', 'sort_order' => 51,
                'question_fr' => "Peut-on lier les sorties de stock à un projet ?",
                'answer_fr'   => "Oui. Chaque mouvement de sortie peut être rattaché à un projet, ce qui permet de suivre le coût réel des matériaux par chantier.",
                'question_en' => "Can stock outflows be linked to a project?",
                'answer_en'   => "Yes. Each outflow can be linked to a project, allowing you to track the actual cost of materials per site.",
            ],
            ['category' => 'stocks', 'sort_order' => 52,
                'question_fr' => "Comment gérer les achats de matériaux ?",
                'answer_fr'   => "Le module Achats permet de créer des bons de commande, de les envoyer aux fournisseurs et de réceptionner les livraisons. Le stock est mis à jour automatiquement à la réception.",
                'question_en' => "How do I manage material purchases?",
                'answer_en'   => "The Purchasing module lets you create purchase orders, send them to suppliers and receive deliveries. Stock is updated automatically on receipt.",
            ],

            // ── QHSE ─────────────────────────────────────────────────────────
            ['category' => 'qhse', 'sort_order' => 60,
                'question_fr' => "Qu'est-ce que le module QHSE ?",
                'answer_fr'   => "Le module QHSE (Qualité, Hygiène, Sécurité, Environnement) permet de déclarer et de suivre les incidents, d'enregistrer les non-conformités, de gérer les audits et de produire des rapports de sécurité.",
                'question_en' => "What is the QHSE module?",
                'answer_en'   => "The QHSE (Quality, Health, Safety, Environment) module lets you declare and track incidents, record non-conformances, manage audits and produce safety reports.",
            ],
            ['category' => 'qhse', 'sort_order' => 61,
                'question_fr' => "Comment déclarer un incident de chantier ?",
                'answer_fr'   => "Dans HSE → Incidents, cliquez sur « Déclarer un incident ». Renseignez la date, le site, la gravité, les personnes impliquées et les mesures prises. Un rapport PDF est générable immédiatement.",
                'question_en' => "How do I report a site incident?",
                'answer_en'   => "In HSE → Incidents, click 'Report an incident'. Fill in the date, site, severity, people involved and actions taken. A PDF report can be generated immediately.",
            ],

            // ── Sécurité & Données ────────────────────────────────────────────
            ['category' => 'securite', 'sort_order' => 70,
                'question_fr' => "Mes données sont-elles sécurisées ?",
                'answer_fr'   => "Oui. CONSTRUIRO utilise le chiffrement HTTPS/TLS, l'isolation multi-tenant stricte (vos données sont invisibles des autres entreprises), des sauvegardes quotidiennes et un journal d'audit complet.",
                'question_en' => "Is my data secure?",
                'answer_en'   => "Yes. CONSTRUIRO uses HTTPS/TLS encryption, strict multi-tenant isolation (your data is invisible to other companies), daily backups and a full audit log.",
            ],
            ['category' => 'securite', 'sort_order' => 71,
                'question_fr' => "Comment gérer les droits des utilisateurs ?",
                'answer_fr'   => "CONSTRUIRO utilise un système de rôles et permissions granulaires. En tant qu'administrateur, vous pouvez créer des rôles personnalisés et attribuer des permissions module par module.",
                'question_en' => "How do I manage user permissions?",
                'answer_en'   => "CONSTRUIRO uses a granular roles and permissions system. As an administrator, you can create custom roles and assign permissions module by module.",
            ],
            ['category' => 'securite', 'sort_order' => 72,
                'question_fr' => "Puis-je exporter mes données ?",
                'answer_fr'   => "Oui. Toutes les listes peuvent être exportées en Excel ou PDF. Un export complet de vos données est disponible depuis la page Paramètres → Export.",
                'question_en' => "Can I export my data?",
                'answer_en'   => "Yes. All lists can be exported to Excel or PDF. A full data export is available from Settings → Export.",
            ],
            ['category' => 'securite', 'sort_order' => 73,
                'question_fr' => "Que se passe-t-il si je supprime mon compte ?",
                'answer_fr'   => "Si vous résiliez votre abonnement, vos données sont conservées pendant 90 jours supplémentaires avant suppression définitive, afin de vous permettre un éventuel retour.",
                'question_en' => "What happens if I delete my account?",
                'answer_en'   => "If you cancel your subscription, your data is kept for an additional 90 days before permanent deletion, giving you the option to return.",
            ],

            // ── Technique ─────────────────────────────────────────────────────
            ['category' => 'technique', 'sort_order' => 80,
                'question_fr' => "Quels navigateurs sont supportés ?",
                'answer_fr'   => "CONSTRUIRO fonctionne sur Chrome, Firefox, Edge et Safari (version récente). Internet Explorer n'est pas supporté.",
                'question_en' => "Which browsers are supported?",
                'answer_en'   => "CONSTRUIRO works on Chrome, Firefox, Edge and Safari (recent versions). Internet Explorer is not supported.",
            ],
            ['category' => 'technique', 'sort_order' => 81,
                'question_fr' => "Comment intégrer CONSTRUIRO avec d'autres outils ?",
                'answer_fr'   => "CONSTRUIRO dispose d'une API REST et de webhooks sortants qui permettent de synchroniser les données avec des outils tiers (comptabilité, CRM, ERP parent). La documentation API est disponible dans les paramètres.",
                'question_en' => "How do I integrate CONSTRUIRO with other tools?",
                'answer_en'   => "CONSTRUIRO has a REST API and outgoing webhooks that allow data synchronisation with third-party tools (accounting, CRM, parent ERP). API documentation is available in settings.",
            ],
            ['category' => 'technique', 'sort_order' => 82,
                'question_fr' => "Y a-t-il une application mobile native ?",
                'answer_fr'   => "Pas encore. Cependant, la PWA offre une expérience proche d'une application native. Une application iOS et Android est en cours de développement.",
                'question_en' => "Is there a native mobile app?",
                'answer_en'   => "Not yet. However, the PWA offers an experience close to a native app. An iOS and Android app is in development.",
            ],
            ['category' => 'technique', 'sort_order' => 83,
                'question_fr' => "Comment importer mes données existantes ?",
                'answer_fr'   => "CONSTRUIRO propose un outil d'import universel accessible depuis le menu Import. Il accepte les fichiers CSV et Excel et propose un mapping visuel des colonnes.",
                'question_en' => "How do I import my existing data?",
                'answer_en'   => "CONSTRUIRO offers a universal import tool accessible from the Import menu. It accepts CSV and Excel files and offers a visual column mapping.",
            ],
            ['category' => 'technique', 'sort_order' => 84,
                'question_fr' => "Quelle est la politique de mises à jour ?",
                'answer_fr'   => "CONSTRUIRO est mis à jour régulièrement avec de nouvelles fonctionnalités, des correctifs et des améliorations de performance. Les mises à jour sont transparentes et n'interrompent pas votre activité.",
                'question_en' => "What is the update policy?",
                'answer_en'   => "CONSTRUIRO is updated regularly with new features, fixes and performance improvements. Updates are transparent and do not interrupt your activity.",
            ],

            // ── Support ────────────────────────────────────────────────────────
            ['category' => 'support', 'sort_order' => 90,
                'question_fr' => "Comment contacter le support ?",
                'answer_fr'   => "Vous pouvez ouvrir un ticket de support depuis le menu Support dans l'application, ou écrire à support@construiro.com. Notre équipe répond dans un délai de 24 h ouvrables.",
                'question_en' => "How do I contact support?",
                'answer_en'   => "You can open a support ticket from the Support menu in the app, or email support@construiro.com. Our team responds within 24 business hours.",
            ],
            ['category' => 'support', 'sort_order' => 91,
                'question_fr' => "Y a-t-il une documentation utilisateur ?",
                'answer_fr'   => "Oui. Un guide utilisateur complet est disponible au format PDF (FR/EN) depuis le menu Aide → Télécharger le guide. Un centre d'aide avec des articles et des tutoriels vidéo est également disponible.",
                'question_en' => "Is there user documentation?",
                'answer_en'   => "Yes. A complete user guide is available as PDF (FR/EN) from Help → Download guide. A help centre with articles and video tutorials is also available.",
            ],
            ['category' => 'support', 'sort_order' => 92,
                'question_fr' => "Proposez-vous de la formation ?",
                'answer_fr'   => "Oui. Nous proposons des sessions de formation en ligne (visioconférence) et des formations sur site pour les équipes. Contactez-nous pour un devis.",
                'question_en' => "Do you offer training?",
                'answer_en'   => "Yes. We offer online training sessions (video conference) and on-site training for teams. Contact us for a quote.",
            ],
            ['category' => 'support', 'sort_order' => 93,
                'question_fr' => "Puis-je demander une démonstration ?",
                'answer_fr'   => "Absolument. Remplissez le formulaire de demande de démo sur la page d'accueil et notre équipe vous contactera pour planifier une présentation personnalisée.",
                'question_en' => "Can I request a demonstration?",
                'answer_en'   => "Absolutely. Fill in the demo request form on the homepage and our team will contact you to schedule a personalised presentation.",
            ],

            // ── BI / Rapports ──────────────────────────────────────────────────
            ['category' => 'bi', 'sort_order' => 100,
                'question_fr' => "Quels tableaux de bord sont disponibles ?",
                'answer_fr'   => "Le module BI propose des tableaux de bord pour les projets (coûts, avancement), la trésorerie (flux, soldes), les RH (effectifs, masse salariale) et les ventes (chiffre d'affaires, devis).",
                'question_en' => "What dashboards are available?",
                'answer_en'   => "The BI module offers dashboards for projects (costs, progress), treasury (cash flow, balances), HR (headcount, payroll) and sales (revenue, quotes).",
            ],
            ['category' => 'bi', 'sort_order' => 101,
                'question_fr' => "Peut-on exporter les rapports ?",
                'answer_fr'   => "Oui. Tous les rapports peuvent être exportés en PDF ou Excel depuis le module BI ou depuis chaque module concerné.",
                'question_en' => "Can reports be exported?",
                'answer_en'   => "Yes. All reports can be exported to PDF or Excel from the BI module or from each relevant module.",
            ],
            ['category' => 'bi', 'sort_order' => 102,
                'question_fr' => "Y a-t-il un assistant IA dans CONSTRUIRO ?",
                'answer_fr'   => "Oui. SARA (Smart Assistant for Resource & Analytics) est intégré à CONSTRUIRO. Il peut répondre à vos questions métier, analyser vos données et vous suggérer des actions.",
                'question_en' => "Is there an AI assistant in CONSTRUIRO?",
                'answer_en'   => "Yes. SARA (Smart Assistant for Resource & Analytics) is integrated into CONSTRUIRO. It can answer your business questions, analyse your data and suggest actions.",
            ],

            // ── Trésorerie ────────────────────────────────────────────────────
            ['category' => 'tresorerie', 'sort_order' => 110,
                'question_fr' => "Comment gérer la trésorerie dans CONSTRUIRO ?",
                'answer_fr'   => "Le module Trésorerie vous permet de saisir les encaissements et décaissements, de suivre les soldes de comptes bancaires et de caisses, et d'obtenir une vue prévisionnelle de votre cash-flow.",
                'question_en' => "How do I manage treasury in CONSTRUIRO?",
                'answer_en'   => "The Treasury module lets you record receipts and disbursements, track bank account and cash balances, and get a forward-looking view of your cash flow.",
            ],
            ['category' => 'tresorerie', 'sort_order' => 111,
                'question_fr' => "Peut-on rapprocher les relevés bancaires ?",
                'answer_fr'   => "Oui. Le module de rapprochement bancaire permet d'importer un relevé et de le comparer ligne par ligne avec les opérations enregistrées dans CONSTRUIRO.",
                'question_en' => "Can I reconcile bank statements?",
                'answer_en'   => "Yes. The bank reconciliation module lets you import a statement and compare it line by line with operations recorded in CONSTRUIRO.",
            ],

            // ── Bureau d'études ───────────────────────────────────────────────
            ['category' => 'bureau_etudes', 'sort_order' => 120,
                'question_fr' => "CONSTRUIRO gère-t-il les métrés ?",
                'answer_fr'   => "Oui. Le module Bureau d'études inclut les métrés (quantitatif des travaux), le bordereau de prix unitaires (BPU) et la décomposition du prix global et forfaitaire (DPGF).",
                'question_en' => "Does CONSTRUIRO handle quantity take-offs?",
                'answer_en'   => "Yes. The Design Office module includes quantity take-offs, unit price schedules (BPU) and overall price breakdowns (DPGF).",
            ],
            ['category' => 'bureau_etudes', 'sort_order' => 121,
                'question_fr' => "Peut-on répondre à des appels d'offres depuis CONSTRUIRO ?",
                'answer_fr'   => "Oui. Le module Commercial → Appels d'offres permet de gérer les dossiers d'appel d'offres, de constituer les réponses et de suivre les résultats.",
                'question_en' => "Can I respond to tenders from CONSTRUIRO?",
                'answer_en'   => "Yes. The Commercial → Tenders module lets you manage tender files, prepare responses and track results.",
            ],

            // ── Multiagences ──────────────────────────────────────────────────
            ['category' => 'multiagences', 'sort_order' => 130,
                'question_fr' => "CONSTRUIRO supporte-t-il plusieurs agences ?",
                'answer_fr'   => "Oui (plans Pro et Entreprise). Vous pouvez créer plusieurs agences/filiales au sein de votre entreprise, chacune avec ses propres utilisateurs, projets et données, tout en gardant une vue consolidée.",
                'question_en' => "Does CONSTRUIRO support multiple branches?",
                'answer_en'   => "Yes (Pro and Enterprise plans). You can create multiple branches/subsidiaries within your company, each with their own users, projects and data, while keeping a consolidated view.",
            ],
            ['category' => 'multiagences', 'sort_order' => 131,
                'question_fr' => "Les données des agences sont-elles isolées ?",
                'answer_fr'   => "Oui. Chaque agence voit uniquement ses propres données. Les administrateurs peuvent choisir d'accorder une visibilité croisée entre agences.",
                'question_en' => "Is branch data isolated?",
                'answer_en'   => "Yes. Each branch sees only its own data. Administrators can choose to grant cross-branch visibility.",
            ],

            // ── Contrats ──────────────────────────────────────────────────────
            ['category' => 'contrats', 'sort_order' => 140,
                'question_fr' => "Comment gérer les contrats clients et fournisseurs ?",
                'answer_fr'   => "Le module Contrats permet d'enregistrer les contrats, de suivre leurs échéances, de gérer les avenants et de lier les contrats aux projets et aux factures correspondants.",
                'question_en' => "How do I manage client and supplier contracts?",
                'answer_en'   => "The Contracts module lets you record contracts, track their deadlines, manage amendments and link contracts to corresponding projects and invoices.",
            ],
            ['category' => 'contrats', 'sort_order' => 141,
                'question_fr' => "Peut-on signer des documents électroniquement ?",
                'answer_fr'   => "Oui. Le module Signature électronique permet d'envoyer des documents à signer, de suivre l'état de signature et d'archiver les originaux signés.",
                'question_en' => "Can documents be signed electronically?",
                'answer_en'   => "Yes. The Electronic Signature module lets you send documents for signature, track signing status and archive the signed originals.",
            ],

            // ── Sous-traitance ────────────────────────────────────────────────
            ['category' => 'sous_traitance', 'sort_order' => 150,
                'question_fr' => "Comment gérer la sous-traitance ?",
                'answer_fr'   => "Dans le module Sous-traitants, vous pouvez référencer vos sous-traitants, créer des marchés de sous-traitance, suivre les situations et gérer les retenues de garantie.",
                'question_en' => "How do I manage subcontracting?",
                'answer_en'   => "In the Subcontractors module, you can register your subcontractors, create subcontracts, track progress invoices and manage retention money.",
            ],

            // ── Parc roulant ──────────────────────────────────────────────────
            ['category' => 'parc_roulant', 'sort_order' => 160,
                'question_fr' => "Peut-on gérer le parc de véhicules et d'engins ?",
                'answer_fr'   => "Oui. Le module Parc roulant permet de gérer les véhicules, les engins de chantier, les maintenances préventives, les consommations de carburant et les affectations.",
                'question_en' => "Can I manage vehicles and equipment?",
                'answer_en'   => "Yes. The Fleet module lets you manage vehicles, construction equipment, preventive maintenance, fuel consumption and assignments.",
            ],

            // ── Laboratoire ───────────────────────────────────────────────────
            ['category' => 'laboratoire', 'sort_order' => 170,
                'question_fr' => "À quoi sert le module Laboratoire ?",
                'answer_fr'   => "Le module Laboratoire permet d'enregistrer et de suivre les analyses de matériaux (béton, sol, bitume…), les rapports de contrôle qualité et les résultats d'essais.",
                'question_en' => "What is the Laboratory module for?",
                'answer_en'   => "The Laboratory module lets you record and track material analyses (concrete, soil, asphalt…), quality control reports and test results.",
            ],

            // ── Onboarding ────────────────────────────────────────────────────
            ['category' => 'general', 'sort_order' => 180,
                'question_fr' => "Comment démarrer rapidement avec CONSTRUIRO ?",
                'answer_fr'   => "Après votre inscription, un guide de démarrage rapide s'affiche. Il vous guide pour créer votre première entreprise, inviter vos collègues, importer vos données et créer votre premier projet.",
                'question_en' => "How do I get started quickly with CONSTRUIRO?",
                'answer_en'   => "After registration, a quick-start guide appears. It walks you through creating your first company, inviting colleagues, importing data and creating your first project.",
            ],
            ['category' => 'general', 'sort_order' => 181,
                'question_fr' => "En combien de temps peut-on être opérationnel ?",
                'answer_fr'   => "La plupart des entreprises sont opérationnelles en moins d'une journée. L'import des données existantes (clients, employés, articles) prend généralement 1 à 2 heures.",
                'question_en' => "How long does it take to get up and running?",
                'answer_en'   => "Most companies are up and running in less than a day. Importing existing data (clients, employees, items) typically takes 1 to 2 hours.",
            ],
        ];

        foreach ($faqs as $faq) {
            LandingFaq::updateOrCreate(
                ['question_fr' => $faq['question_fr']],
                $faq + ['is_active' => true]
            );
        }

        $this->command->info('LandingFaqSeeder : ' . count($faqs) . ' FAQs insérées/mises à jour.');
    }
}
