@extends('errors.layout')
@section('code', '403')
@section('title', 'Accès refusé')
@section('emoji', '🚫')
@section('message', 'Vous n\'avez pas les droits nécessaires pour accéder à cette ressource. Contactez votre administrateur si vous pensez que c\'est une erreur.')
