@extends('errors.layout')
@section('code', '404')
@section('title', 'Page introuvable')
@section('emoji', '🔍')
@section('message', 'La page que vous recherchez n\'existe pas ou a été déplacée. Vérifiez l\'URL ou retournez à l\'accueil.')
