@extends('errors.layout')
@section('code', '429')
@section('title', 'Trop de requêtes')
@section('emoji', '🐌')
@section('message', 'Vous avez effectué trop d\'actions en peu de temps. Attendez quelques instants avant de réessayer.')
