@extends('errors.layout')
@section('code', '500')
@section('title', 'Erreur interne du serveur')
@section('emoji', '⚡')
@section('message', 'Une erreur inattendue s\'est produite. Notre équipe technique a été notifiée. Réessayez dans quelques instants.')
