@extends('errors.layout')
@section('code', '503')
@section('title', 'Maintenance en cours')
@section('emoji', '🔧')
@section('message', 'CONSTRUIRO ERP est temporairement indisponible pour maintenance. Nous serons de retour très bientôt.')
