import {
    Activity,
    AlertCircle,
    ArrowDownCircle,
    ArrowLeft,
    ArrowLeftRight,
    ArrowUpCircle,
    BadgeCheck,
    Banknote,
    BarChart3,
    Book,
    Boxes,
    Briefcase,
    Building,
    Building2,
    Calculator,
    Calendar,
    CalendarClock,
    CalendarRange,
    Camera,
    Car,
    Check,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    Circle,
    CircleDollarSign,
    ClipboardCheck,
    ClipboardList,
    Coins,
    Construction,
    Contact,
    Download,
    ExternalLink,
    FileDown,
    FileSignature,
    FileSpreadsheet,
    FileText,
    Files,
    Fingerprint,
    FlaskConical,
    Folder,
    FolderKanban,
    FolderOpen,
    Forklift,
    Fuel,
    GanttChart,
    Gavel,
    GraduationCap,
    Handshake,
    HardHat,
    Hash,
    Home,
    Info,
    KeyRound,
    Landmark,
    LayoutDashboard,
    LifeBuoy,
    Lightbulb,
    List,
    ListChecks,
    ListPlus,
    MapPin,
    Menu,
    MessageCircle,
    Package,
    Pencil,
    PenLine,
    PenTool,
    Percent,
    PieChart,
    PlugZap,
    Plus,
    Printer,
    Receipt,
    Ruler,
    Scale,
    Search,
    Send,
    Settings,
    ShieldAlert,
    ShieldCheck,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Tags,
    Target,
    Tractor,
    Trash2,
    TrendingUp,
    Truck,
    User,
    UserPlus,
    Users,
    UsersRound,
    Wallet,
    Warehouse,
    Wrench,
    X,
} from 'lucide-react';

/**
 * Icône dynamique : rend l'icône Lucide dont le nom (kebab-case, comme dans
 * config/construiro.php) est passé en prop. Repli sur « Circle » si inconnu.
 *
 * Les imports individuels (au lieu de `{ icons }`) permettent à Vite de
 * tree-shaker lucide-react et de ne bundler que les icônes réellement utilisées.
 */
const ICONS = {
    activity: Activity,
    'alert-circle': AlertCircle,
    'arrow-down-circle': ArrowDownCircle,
    'arrow-left': ArrowLeft,
    'arrow-left-right': ArrowLeftRight,
    'arrow-up-circle': ArrowUpCircle,
    'badge-check': BadgeCheck,
    banknote: Banknote,
    'bar-chart-3': BarChart3,
    book: Book,
    boxes: Boxes,
    briefcase: Briefcase,
    building: Building,
    'building-2': Building2,
    calculator: Calculator,
    calendar: Calendar,
    'calendar-clock': CalendarClock,
    'calendar-range': CalendarRange,
    camera: Camera,
    car: Car,
    check: Check,
    'check-circle': CheckCircle,
    'check-circle-2': CheckCircle2,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    circle: Circle,
    'circle-dollar-sign': CircleDollarSign,
    'clipboard-check': ClipboardCheck,
    'clipboard-list': ClipboardList,
    coins: Coins,
    construction: Construction,
    contact: Contact,
    download: Download,
    'external-link': ExternalLink,
    'file-down': FileDown,
    'file-signature': FileSignature,
    'file-spreadsheet': FileSpreadsheet,
    'file-text': FileText,
    files: Files,
    fingerprint: Fingerprint,
    'flask-conical': FlaskConical,
    folder: Folder,
    'folder-kanban': FolderKanban,
    'folder-open': FolderOpen,
    forklift: Forklift,
    fuel: Fuel,
    'gantt-chart': GanttChart,
    gavel: Gavel,
    'graduation-cap': GraduationCap,
    handshake: Handshake,
    'hard-hat': HardHat,
    hash: Hash,
    home: Home,
    info: Info,
    'key-round': KeyRound,
    landmark: Landmark,
    'layout-dashboard': LayoutDashboard,
    'life-buoy': LifeBuoy,
    lightbulb: Lightbulb,
    list: List,
    'list-checks': ListChecks,
    'list-plus': ListPlus,
    'map-pin': MapPin,
    menu: Menu,
    'message-circle': MessageCircle,
    package: Package,
    pencil: Pencil,
    'pen-line': PenLine,
    'pen-tool': PenTool,
    percent: Percent,
    'pie-chart': PieChart,
    'plug-zap': PlugZap,
    plus: Plus,
    printer: Printer,
    receipt: Receipt,
    ruler: Ruler,
    scale: Scale,
    search: Search,
    send: Send,
    settings: Settings,
    'shield-alert': ShieldAlert,
    'shield-check': ShieldCheck,
    'shopping-cart': ShoppingCart,
    smartphone: Smartphone,
    sparkles: Sparkles,
    tags: Tags,
    target: Target,
    tractor: Tractor,
    'trash-2': Trash2,
    'trending-up': TrendingUp,
    truck: Truck,
    user: User,
    'user-plus': UserPlus,
    users: Users,
    'users-round': UsersRound,
    wallet: Wallet,
    warehouse: Warehouse,
    wrench: Wrench,
    x: X,
};

export default function Icon({ name, className = 'h-5 w-5', ...props }) {
    const LucideIcon = ICONS[name] ?? Circle;
    return <LucideIcon className={className} {...props} />;
}
